# Generated by Django 5.1.5 on 2025-02-04 15:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Charateristic",
            new_name="Characteristic",
        ),
    ]
